import Foundation

@testable import ZILFCore

/// A test harness that allows running games without blocking for input.
public class GameTestHarness<T: ZilfGame> {
    /// The game under test.
    public let game: T

    /// The game engine instance.
    public let engine: GameEngine

    /// Output capture for assertions.
    public let outputCapture = OutputCapture()

    /// Initialize a test harness for a specific game.
    ///
    /// - Parameter game: The game to test.
    public init(for game: T) {
        self.game = game
        self.engine = GameEngine(
            game: game,
            console: outputCapture
        )
    }

    /// Execute a command and return the output.
    /// 
    /// - Parameter command: The command to execute.
    /// - Returns: Array of output strings generated by the command.
    public func execute(_ command: String) -> [String] {
        // Clear previous output
        outputCapture.clearCapturedOutput()

        // Parse and execute
        let cmd = engine.parser.parse(command, in: engine.world)
        engine.executeCommand(cmd)

        return outputCapture.capturedOutput
    }
    
    /// <#Description#>.
    /// - Returns: <#description#>.
    @discardableResult
    public func flush() -> String {
        outputCapture.flush()
    }

    /// Initialize the game (show welcome text, etc.).
    public func initialize() {
        engine.initialize()
    }
}
