import Foundation

@testable import ZILFCore

/// A test harness that allows running games without blocking for input.
public class GameTestHarness<T: ZilfGame> {
    /// The game under test.
    public let game: T

    /// The game engine instance.
    public let engine: GameEngine

    /// Output capture for assertions.
    public let console = CaptureConsole()

    /// Initialize a test harness for a specific game.
    ///
    /// - Parameter game: The game to test.
    public init(for game: T) {
        self.game = game
        self.engine = GameEngine(
            game: game,
            console: console
        )
        engine.updateState(to: .running)
    }

    /// Execute a command and return the output.
    /// 
    /// - Parameter commandString: The command to execute.
    /// - Returns: Array of output strings generated by the command.
    public func execute(_ commandString: String) throws -> [String] {
        // Clear previous output
        console.clearCapturedOutput()

        // Parse and execute
        let command = engine.parser.parse(commandString, in: engine.world)
        try engine.executeCommand(command)

        return console.capturedOutput
    }
    
    /// <#Description#>.
    /// - Returns: <#description#>.
    @discardableResult
    public func flush() -> String {
        console.flush()
    }

    /// Initialize the game (show welcome text, etc.).
    public func initialize() throws {
        try engine.initialize()
    }
}
