import Foundation
import ZILFCore

/// A test harness that allows running games without blocking for input
public class GameTestHarness<T: ZilfGame> {
    /// The game under test
    public let game: T

    /// The game engine instance
    public let engine: GameEngine

    /// Output capture for assertions
    public let outputCapture = OutputCapture()

    /// Initialize a test harness for a specific game
    /// - Parameter game: The game to test
    public init(game: T) {
        self.game = game
        self.engine = GameEngine(game: game, ui: .standard)

        // Replace the engine's output manager
        self.engine.outputManager = outputCapture
    }

    /// Execute a command and return the output
    /// - Parameter command: The command to execute
    /// - Returns: Array of output strings generated by the command
    public func execute(_ command: String) -> [String] {
        // Clear previous output
        outputCapture.clearCapturedOutput()

        // Parse and execute
        let cmd = engine.parser.parse(command)
        engine.executeCommand(cmd)

        return outputCapture.capturedOutput
    }

    /// Initialize the game (show welcome text, etc.)
    public func initialize() {
        engine.initialize()
    }
}

/// Output capture for testing
public class OutputCapture: OutputManager {
    private(set) public var capturedOutput: [String] = []

    public init() {}

    public func output(_ message: String) {
        capturedOutput.append(message)
    }

    public func clearCapturedOutput() {
        capturedOutput.removeAll()
    }

    public func updateStatusLine(location: String, score: Int, moves: Int) {
        // Not needed for testing
    }

    public func getInput(prompt: String) -> String? {
        // This should never be called during testing
        return nil
    }

    public func shutdown() {
        // Not needed for testing
    }
}
